# Generated by Django 5.2.2 on 2025-07-10 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='doctor_id',
            new_name='id',
        ),
    ]
